import { StyleSheet, Platform } from 'react-native';

export const sidebarStyles = StyleSheet.create({
  backdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  container: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    width: '78%',
    backgroundColor: '#f7f8fa',
    borderTopRightRadius: 18,
    borderBottomRightRadius: 18,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 8,
    ...Platform.select({ ios: { zIndex: 100 }, android: {} }),
  },
  safeArea: {
    flex: 1,
  },
  header: {
    padding: 14,
    backgroundColor: '#007AFF',
    borderTopRightRadius: 18,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
    letterSpacing: 0.2,
  },
  userInfo: {
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#e9ecef',
    backgroundColor: '#fff',
  },
  userInfoLabel: {
    fontSize: 12,
    color: '#6c757d',
    marginBottom: 2,
  },
  userInfoValue: {
    fontSize: 13,
    fontWeight: '600',
    color: '#212529',
    marginBottom: 8,
  },
  divider: {
    height: 1,
    backgroundColor: '#e9ecef',
    marginVertical: 4,
  },
  menuContainer: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  menuItem: {
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 20,
    marginHorizontal: 8,
    marginVertical: 2,
  },
  menuText: {
    fontSize: 14,
    color: '#212529',
    fontWeight: '500',
  },
  logoutButton: {
    paddingVertical: 10,
    margin: 10,
    borderRadius: 18,
    backgroundColor: '#dc3545',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#dc3545',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  logoutText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0.1,
  },
}); 